-- Only for use with GMod's language library, hence it is only clientside
-- When translating, only change the strings on the right!

ArcCW.PhraseTable = {
    ["en"] = {
        -- Generic
        ["arccw.adminonly"]                      = "These options require admin privileges to change. They are automatically networked in multiplayer games.",
        ["arccw.clientcfg"]                      = "All options in this menu can be customized by players, and do not need admin privileges.",
        -- Menus
        ["arccw.menus.hud"]                      = "HUD",
        ["arccw.menus.client"]                   = "Client",
        ["arccw.menus.vmodel"]                   = "Viewmodel",
        ["arccw.menus.perf"]                     = "Performance",
        ["arccw.menus.server"]                   = "Server",
        ["arccw.menus.mults"]                    = "Multipliers",
        ["arccw.menus.npcs"]                     = "NPCs",
        ["arccw.menus.atts"]                     = "Attachments",
        ["arccw.menus.ammo"]                     = "Ammo",
        ["arccw.menus.dev"]                    = "Developer",
        ["arccw.menus.xhair"]                    = "Crosshair",
        ["arccw.menus.bullet"]                   = "Bullet Physics",
        -- ArcCW_Options_Ammo
        ["arccw.cvar.ammo_detonationmode"]       = "Ammo Detonation Mode",
        ["arccw.cvar.ammo_detonationmode.desc"]  = "-1 - don't explode\n 0 - simple explosion\n 1 - fragmentation\n 2 - frag + burning",
        ["arccw.cvar.ammo_autopickup"]           = "Auto Pickup",
        ["arccw.cvar.ammo_largetrigger"]         = "Large Pickup Trigger",
        ["arccw.cvar.ammo_rareskin"]             = "Rare Skin Chance",
        ["arccw.cvar.ammo_chaindet"]             = "Chain Detonation",
        ["arccw.cvar.mult_ammohealth"]           = "Ammo Health (-1 for indestructible)",
        ["arccw.cvar.mult_ammoamount"]           = "Ammo Amount",
        -- ArcCW_Options_HUD
        ["arccw.cvar.hud_showhealth"]            = "Show Health",
        ["arccw.cvar.hud_showhealth.desc"]       = "Draw a custom health & armor counter.",
        ["arccw.cvar.hud_showammo"]              = "Show Ammo",
        ["arccw.cvar.hud_showammo.desc"]         = "Custom ammo counter with firemode info and weapon name.",
        ["arccw.cvar.hud_3dfun"]                 = "Use 3D2D Ammo HUD",
        ["arccw.cvar.hud_3dfun.desc"]            = "Use a 3D2D ammo counter.",
        ["arccw.cvar.hud_minimal"]               = "Allow Backup Ammo HUD",
        ["arccw.cvar.hud_minimal.desc"]          = "If we can't draw our own HUD, use a minimal one.",
        ["arccw.cvar.hud_forceshow"]             = "Force HUD On",
        ["arccw.cvar.hud_forceshow.desc"]        = "Don't play by the rules and draw our HUD anyways.",
        ["arccw.cvar.hudpos_deadzone_x"]         = "Deadzone X",
        ["arccw.cvar.hudpos_deadzone_y"]         = "Deadzone Y",
        ["arccw.cvar.hudpos_deadzone.desc"]      = "Use ArcCW on your HDTV!",
        ["arccw.cvar.hudpos_size"]               = "HUD and Font Size",
        ["arccw.cvar.hudpos_size.desc"]          = "Custom HUD scaling.",
        -- ArcCW_Options_Bullet
        ["arccw.cvar.bullet_enable"]             = "Physical Bullets",
        ["arccw.cvar.bullet_gravity"]            = "Gravity",
        ["arccw.cvar.bullet_drag"]               = "Drag",
        ["arccw.cvar.bullet_lifetime"]           = "Despawn Time",
        ["arccw.cvar.bullet_velocity"]           = "Multiply Velocity",
        ["arccw.cvar.bullet_imaginary"]          = "Imaginary Bullets",
        ["arccw.cvar.bullet_imaginary.desc"]     = "Bullets will appear to continue to travel through the 3D skybox.",
        -- ArcCW_Options_Client
        ["arccw.cvar.automaticreload"]           = "Automatic Reload",
        ["arccw.cvar.automaticreload.desc"]      = "Automatically reload when your clip is empty.",
        ["arccw.cvar.toggleads"]                 = "Toggle Aim",
        ["arccw.cvar.altfcgkey"]                 = "E+R To Toggle Firemode (Disables +ZOOM)",
        ["arccw.cvar.altubglkey"]                = "E+RMB To Toggle UBGL (Disables 2x +ZOOM)",
        ["arccw.cvar.altsafety"]                 = "Hold Walk to Toggle Safety",
        ["arccw.cvar.altlaserkey"]               = "E+WALK To Toggle Laser (Default WALK+E)",
        ["arccw.cvar.autosave"]                  = "Autosave Attachments",
        ["arccw.cvar.autosave.desc"]             = "Attempt to re-equip the last equipped set of attachments on weapon pickup.",
        ["arccw.cvar.embracetradition"]          = "Classic Customization HUD",
        ["arccw.cvar.embracetradition.desc"]     = "Use the classic bulky customization HUD. Embrace tradition. Good on 4:3.",
        ["arccw.cvar.glare"]                     = "Scope Glare",
        ["arccw.cvar.glare.desc"]                = "Glare visible on your scope lens when aiming.",
        ["arccw.cvar.shake"]                     = "Screen Shake",
        ["arccw.cvar.shake_info"]                = "Aggressive snap when you shoot a weapon.",
        ["arccw.cvar.2d3d"]                      = "Floating Help Text",
        ["arccw.cvar.2d3d_info"]                 = "Text that floats over dropped weapons.",
        ["arccw.cvar.attinv_hideunowned"]        = "Hide Unowned Attachments",
        ["arccw.cvar.attinv_darkunowned"]        = "Grey Out Unowned Attachments",
        ["arccw.cvar.attinv_onlyinspect"]        = "Hide Customization UI",
        ["arccw.cvar.attinv_simpleproscons"]     = "Simple Pros And Cons",
        ["arccw.cvar.attinv_closeonhurt"]        = "Close menu on damage taken",
        ["arccw.cvar.language"]                  = "Language",
        ["arccw.cvar.language_info"]             = "Override the language. Leave blank for gmod_language.",
        ["arccw.cvar.font"]                      = "Font",
        ["arccw.cvar.font_info"]                 = "Override the font. Leave blank for default.",
        -- ArcCW_Options_Perf
        ["arccw.performance"]                    = "The options below may change performance.",
        ["arccw.cvar.cheapscopes"]               = "Cheap Scopes",
        ["arccw.cvar.cheapscopes.desc"]          = "A cheaper PIP scope implementation that is very low quality but saves a significant amount of performance. Scoped weapons will appear to clip into surfaces.\nWill reduce scope quality!",
        ["arccw.cvar.flatscopes"]                = "Flat Scopes",
        ["arccw.cvar.flatscopes.desc"]           = "For the ultimate performance gain.\nUse a traditional-style scope implementation that's not very impressive, but actually saves performance relative to even being unscoped.",
        ["arccw.cvar.muzzleeffects"]             = "Enable World Muzzle Effects",
        ["arccw.cvar.fastmuzzles"]               = "Low Performance Muzzle Effects",
        ["arccw.cvar.shelleffects"]              = "Enable World Case Effects",
        ["arccw.cvar.att_showothers"]            = "Show World Attachments",
        ["arccw.cvar.shelltime"]                 = "Case Lifetime",
        ["arccw.cvar.blur"]                      = "Customization Blur",
        ["arccw.cvar.blur_toytown"]              = "Aim Blur",
        ["arccw.cvar.visibility"]                = "Worldmodel Visibility",
        ["arccw.cvar.visibility.desc"]           = "Attachments will not render past this distance. -1 for always render.",
        -- ArcCW_Options_Viewmodel
        ["arccw.cvar.vm_coolsway"]               = "Custom Swaying",
        ["arccw.cvar.vm_coolview"]               = "Custom Camera Movement",
        ["arccw.cvar.vm_right"]                  = "Viewmodel Right",
        ["arccw.cvar.vm_forward"]                = "Viewmodel Forward",
        ["arccw.cvar.vm_up"]                     = "Viewmodel Up",
        ["arccw.cvar.vm_offsetwarn"]             = "Warning! Viewmodel offset settings may cause clipping or other undesired effects!",
        ["arccw.cvar.vm_sway_sprint"]            = "Sprint Bob", -- This is intentionally flipped
        ["arccw.cvar.vm_bob_sprint"]             = "Sprint Sway", -- Ditto
        ["arccw.cvar.vm_swaywarn"]               = "The following only applies when Custom Swaying is enabled",
        ["arccw.cvar.vm_lookymult"]              = "Horizontal Look Sway",
        ["arccw.cvar.vm_lookxmult"]              = "Vertical Look Sway",
        ["arccw.cvar.vm_swayxmult"]              = "Bob Right",
        ["arccw.cvar.vm_swayymult"]              = "Bob Forward",
        ["arccw.cvar.vm_swayzmult"]              = "Bob Up",
        ["arccw.cvar.vm_swaywigglemult"]         = "Bob Wiggle",
        ["arccw.cvar.vm_swayspeedmult"]          = "Bob Speed",
        ["arccw.cvar.vm_swayrotatemult"]         = "Bob Rotate",

        ["arccw.cvar.vm_accelmult"]              = "Sway Tightness",
        ["arccw.cvar.vm_viewwarn"]               = "The following only applies when Custom Camera Movement is enabled",
        ["arccw.cvar.vm_coolviewmult"]           = "View Move Multiplier",
        -- ArcCW_Options_Crosshair
        ["arccw.crosshair.tfa"]                  = "TFA",
        ["arccw.crosshair.cw2"]                  = "CW 2.0",
        ["arccw.crosshair.cs"]                   = "Counter-Strike",
        ["arccw.crosshair.light"]                = "Lightweight",
        ["arccw.cvar.crosshair"]                 = "Enable Crosshair",
        ["arccw.cvar.crosshair_length"]          = "Crosshair Length",
        ["arccw.cvar.crosshair_thickness"]       = "Crosshair Thickness",
        ["arccw.cvar.crosshair_gap"]             = "Crosshair Gap Scale",
        ["arccw.cvar.crosshair_dot"]             = "Show Center Dot",
        ["arccw.cvar.crosshair_shotgun"]         = "Use Shotgun Prongs",
        ["arccw.cvar.crosshair_equip"]           = "Use Equipment Prongs",
        ["arccw.cvar.crosshair_static"]          = "Static Crosshair",
        ["arccw.cvar.crosshair_clump"]           = "Use CW2-Style Clump Circle",
        ["arccw.cvar.crosshair_clump_outline"]   = "Clump Circle Outline",
        ["arccw.cvar.crosshair_clump_always"]    = "Clump Circle Always On",
        ["arccw.cvar.crosshair_clr"]             = "Crosshair Color",
        ["arccw.cvar.crosshair_outline"]         = "Outline Size",
        ["arccw.cvar.crosshair_outline_clr"]     = "Outline Color",
        ["arccw.cvar.scope_clr"]                 = "Sight Color",
        -- ArcCW_Options_Mults
        ["arccw.cvar.mult_damage"]               = "Damage",
        ["arccw.cvar.mult_npcdamage"]            = "NPC Damage",
        ["arccw.cvar.mult_range"]                = "Range",
        ["arccw.cvar.mult_recoil"]               = "Recoil",
        ["arccw.cvar.mult_penetration"]          = "Penetration",
        ["arccw.cvar.mult_hipfire"]              = "Hip Dispersion",
        ["arccw.cvar.mult_movedisp"]             = "Move Dispersion",
        ["arccw.cvar.mult_reloadtime"]           = "Reload Time",
        ["arccw.cvar.mult_sighttime"]            = "ADS Time",
        ["arccw.cvar.mult_defaultclip"]          = "Default Clip",
        ["arccw.cvar.mult_attchance"]            = "Random Att. Chance",
        ["arccw.cvar.mult_damage"]               = "Damage",
        ["arccw.cvar.mult_npcdamage"]            = "NPC Damage",
        ["arccw.cvar.mult_range"]                = "Range",
        ["arccw.cvar.mult_recoil"]               = "Recoil",
        ["arccw.cvar.mult_penetration"]          = "Penetration",
        ["arccw.cvar.mult_hipfire"]              = "Hip Dispersion",
        ["arccw.cvar.mult_movedisp"]             = "Move Dispersion",
        ["arccw.cvar.mult_reloadtime"]           = "Reload Time",
        ["arccw.cvar.mult_sighttime"]            = "ADS Time",
        ["arccw.cvar.mult_defaultclip"]          = "Default Clip",
        ["arccw.cvar.mult_attchance"]            = "Random Att. Chance",
        -- ArcCW_Options_Atts
        ["arccw.attdesc1"]                       = "ArcCW supports attachment inventory style behaviour (Like ACT3) as well as attachment locking style behaviour (Like CW2.0) as well as giving everyone all attachments for free (Like TFA Base).",
        ["arccw.attdesc2"]                       = "Leave all options off for ACT3 style attachment inventory behaviour.",
        ["arccw.cvar.attinv_free"]               = "Free Attachments",
        ["arccw.cvar.attinv_lockmode"]           = "Attachment Locking",
        ["arccw.cvar.attinv_loseondie.desc"]     = "Lose Attachments Modes:\n0 - Disable\n1 = Removed on death\n2 = Drop Attachment Box on death",
        ["arccw.cvar.attinv_loseondie"]          = "Lose Attachments Mode",
        ["arccw.cvar.atts_pickx.desc"]           = "Pick X behaviour allows you to set a limit on attachments that can be placed on any weapon.\n0 = unlimited.",
        ["arccw.cvar.atts_pickx"]                = "Pick X",
        ["arccw.cvar.enable_dropping"]           = "Attachment Dropping",
        ["arccw.cvar.atts_spawnrand"]            = "Random Attachments on Spawn",
        ["arccw.cvar.atts_ubglautoload"]         = "Underbarrel Weapons Automatically Loaded",
        ["arccw.blacklist"]                      = "Blacklist Menu",
        -- ArcCW_Options_Server
        ["arccw.cvar.enable_penetration"]        = "Enable Penetration",
        ["arccw.cvar.enable_customization"]      = "Enable Customization",
        ["arccw.cvar.truenames"]                 = "True Names (Requires Restart)",
        ["arccw.cvar.equipmentammo.desc"]        = "There is a limit of 255 ammo types, and enabling this option can cause problems related to this. Requires restart.",
        ["arccw.cvar.equipmentammo"]             = "Equipment Unique Ammo Types",
        ["arccw.cvar.equipmentsingleton.desc"]   = "Singletons can be used once and then remove themselves from your inventory. Requires restart.",
        ["arccw.cvar.equipmentsingleton"]        = "Grenade/Equipment Singleton",
        ["arccw.cvar.equipmenttime"]             = "Equipment Self-Destruct Time",
        ["arccw.cvar.throwinertia"]              = "Grenade Inherit Velocity",
        ["arccw.cvar.limityear_enable"]          = "Enable Year Limit",
        ["arccw.cvar.limityear"]                 = "Year Limit",
        ["arccw.cvar.override_crosshair_off"]    = "Force Disable Crosshair",
        ["arccw.cvar.override_deploychambered"]  = "Deploy with Rounds Chambered",
        ["arccw.cvar.override_barrellength"]     = "Enable Near-Walling",
        ["arccw.cvar.doorbust"]                  = "Enable Door-Busting",
        ["arccw.cvar.desync"]                    = "Desync Bullets",
        ["arccw.cvar.desync.desc"]               = "Desync bullets between the server and the client, making the nospread cheat useless.",
        ["arccw.cvar.weakensounds"]              = "Weaken Sounds",
        ["arccw.cvar.weakensounds.desc"]         = "Reduce all weapons' firing volume by this much decibels, making it easier to hide shooting sounds. Clamped to 60-150dB.",
        -- ArcCW_Options_Dev
        ["arccw.dev_info1"]                      = "These are primarily related to attachments and are of use to developers only.",
        ["arccw.dev_info2"]                      = "Settings will not save.",
        ["arccw.cvar.dev_reloadonadmincleanup"]  = "Reload on Admin Cleanup",
        ["arccw.cvar.dev_reloadonadmincleanup.desc"]    = "Disabled by default.\nDoing an admin cleanup will reload all attachment data.",
        ["arccw.cvar.dev_registerentities"]      = "Register Att. Entities",
        ["arccw.cvar.dev_registerentities.desc"] = "Enabled by default.\nCreates entities for ArcCW attachments. Increases time to reload attachment data.",
        ["arccw.cvar.dev_reloadatts"]            = "Reload Attachment Data",
        ["arccw.cvar.dev_reloadatts.desc"]       = "Reloads attachment data. Use after making a change to an attachment.",
        -- TTT Menus
        ["arccw.cvar.attinv_loseondie.help"]     = "If enabled, players lose attachment on death and round end.",
        ["arccw.cvar.ammo_detonationmode.help"]  = "Determines what happens if ammo boxes are destroyed.",
        ["arccw.cvar.equipmenttime.help"]        = "Applies to deployable equipment like Claymores, in seconds.",
        ["arccw.cvar.ttt_bodyattinfo"]           = "Body Attachment Info",
        ["arccw.cvar.ttt_bodyattinfo.help"]      = "If enabled, searching a body will reveal the attachments on the weapon used to kill someone.",
        ["arccw.cvar.ttt_bodyattinfo.desc"]      = "0 - Off; 1 - Detectives can see; 2 - Everyone can see",
        ["arccw.cvar.attinv_free.help"]          = "If enabled, players have access to all attachments.\nCustomization mode may still restrict them from using them.",
        ["arccw.cvar.attinv_lockmode.help"]      = "If enabled, picking up one attachment unlocks it for every weapon, a-la CW2.",
        ["arccw.cvar.ttt_weakensounds"]          = "Weaken Sounds",
        ["arccw.cvar.ttt_weakensounds.help"]     = "Reduces all firearm volume by 20dB, making shots easier to hide.",
        ["arccw.cvar.enable_customization.help"] = "If disabled, nobody can customize. This overrides Customization Mode.",
        ["arccw.cvar.ttt_replace"]               = "Auto-replace Weapons",
        ["arccw.cvar.ttt_replaceammo"]           = "Auto-replace Ammo",
        ["arccw.cvar.ttt_atts"]                  = "Randomize Attachments",
        ["arccw.cvar.ttt_customizemode"]         = "Customization Mode",
        ["arccw.cvar.ttt_customizemode.desc"]    = "0 - No restrictions; 1 - Restricted; 2 - Pregame only; 3 - Traitor/Detective only",
        ["arccw.cvar.ttt_rolecrosshair"]         = "Enable role-based crosshair color",
        ["arccw.cvar.ttt_inforoundstart"]        = "Enable round startup info",
    },
    ["kr"] = {
        -- Generic
        ["arccw.adminonly"]                      = "이 옵션들을 변경하려면 관리자 권한이 필요하며, 멀티플레이 환경에서는 변경 시 서버에 반영됩니다.",
        ["arccw.clientcfg"]                      = "이 메뉴의 모든 옵션은 관리자 권한 없이 커스텀할 수 있습니다.",
        -- Menus
        ["arccw.menus.hud"]                      = "HUD",
        ["arccw.menus.client"]                   = "사용자",
        ["arccw.menus.vmodel"]                   = "뷰 모델",
        ["arccw.menus.perf"]                     = "성능",
        ["arccw.menus.server"]                   = "서버",
        ["arccw.menus.mults"]                    = "배율",
        ["arccw.menus.npcs"]                     = "NPCs",
        ["arccw.menus.atts"]                     = "부착물",
        ["arccw.menus.ammo"]                     = "탄약",
        ["arccw.menus.dev"]                    = "개발자",
        ["arccw.menus.xhair"]                    = "조준점",
        ["arccw.menus.bullet"]                   = "탄환 물리",
        -- ArcCW_Options_Ammo
        ["arccw.cvar.ammo_detonationmode"]       = "탄약 폭발 모드",
        ["arccw.cvar.ammo_detonationmode.desc"]  = "-1 - 폭발하지 않음\n 0 - 단순한 폭발\n 1 - 파편을 포함한 폭발\n 2 - 파편 및 화재를 포함한 폭발",
        ["arccw.cvar.ammo_autopickup"]           = "자동 획득",
        ["arccw.cvar.ammo_largetrigger"]         = "대량 획득 트리거",
        ["arccw.cvar.ammo_rareskin"]             = "레어 스킨 확률",
        ["arccw.cvar.ammo_chaindet"]             = "연쇄 폭발",
        ["arccw.cvar.mult_ammohealth"]           = "탄약 체력 (-1 일 경우 파괴 불가능)",
        ["arccw.cvar.mult_ammoamount"]           = "탄약량",
        -- ArcCW_Options_HUD
        ["arccw.cvar.hud_showhealth"]            = "체력 허드",
        ["arccw.cvar.hud_showhealth.desc"]       = "커스텀 체력 및 아머 허드를 사용합니다.",
        ["arccw.cvar.hud_showammo"]              = "탄약 허드",
        ["arccw.cvar.hud_showammo.desc"]         = "커스텀 탄약 표시기, 사격 모드 및 무기 정보 허드를 사용합니다.",
        ["arccw.cvar.hud_3dfun"]                 = "3D2D 탄약 허드 사용",
        ["arccw.cvar.hud_3dfun.desc"]            = "3D2D 탄약 허드를 사용할지에 대한 여부입니다.",
        ["arccw.cvar.hud_minimal"]               = "보조 탄약 허드 사용",
        ["arccw.cvar.hud_minimal.desc"]          = "만약 기본 탄약 허드를 사용할 수 없는 경우, 간소화된 허드를 사용할지에 대한 여부입니다.",
        ["arccw.cvar.hud_forceshow"]             = "허드 강제 사용",
        ["arccw.cvar.hud_forceshow.desc"]        = "모든 규칙을 무시하고 허드를 사용할지에 대한 여부입니다.",
        ["arccw.cvar.hudpos_deadzone_x"]         = "X 데드존",
        ["arccw.cvar.hudpos_deadzone_y"]         = "Y 데드존",
        ["arccw.cvar.hudpos_deadzone.desc"]      = "HDTV에서 ArcCW를 사용하세요.",
        ["arccw.cvar.hudpos_size"]               = "허드 및 폰트 크기",
        ["arccw.cvar.hudpos_size.desc"]          = "허드에 대한 스케일 커스터마이징.",
        -- ArcCW_Options_Bullet
        ["arccw.cvar.bullet_enable"]             = "탄환 물리",
        ["arccw.cvar.bullet_gravity"]            = "중력",
        ["arccw.cvar.bullet_drag"]               = "드래그",
        ["arccw.cvar.bullet_lifetime"]           = "소멸 시간",
        ["arccw.cvar.bullet_velocity"]           = "탄환 속도 배율",
        ["arccw.cvar.bullet_imaginary"]          = "가상 탄환",
        ["arccw.cvar.bullet_imaginary.desc"]     = "탄환이 맵의 3D 스카이 박스를 넘어서도 보여질지에 대한 여부입니다.",
        -- ArcCW_Options_Client
        ["arccw.cvar.automaticreload"]           = "자동 재장전",
        ["arccw.cvar.automaticreload.desc"]      = "탄창의 탄약을 모두 소비하였을 때 자동으로 재장전할지에 대한 여부입니다.",
        ["arccw.cvar.toggleads"]                 = "토글식 조준",
        ["arccw.cvar.altfcgkey"]                 = "사격 모드 - E+R 단축키 사용 (비활성 시 +ZOOM)",
        ["arccw.cvar.altubglkey"]                = "하단 부착식 무기 - E+RMB 단축키 사용 (비활성 시 +ZOOM 2번)",
        ["arccw.cvar.altsafety"]                 = "걷기 키를 오래눌러 사격 모드를 안전으로 변경",
        ["arccw.cvar.altlaserkey"]               = "레이저 - E+WALK 단축키 사용 (기본 값 WALK+E)",
        ["arccw.cvar.autosave"]                  = "부착물 자동 저장",
        ["arccw.cvar.autosave.desc"]             = "새로운 무기 습득 시 마지막으로 사용한 부착물을 자동으로 재장착할지에 대한 여부입니다.",
        ["arccw.cvar.embracetradition"]          = "클래식 커스텀 허드",
        ["arccw.cvar.embracetradition.desc"]     = "클래식 커스텀 허드를 사용할지에 대한 여부입니다. 4:3 비율 환경에 적합합니다.",
        ["arccw.cvar.glare"]                     = "조준경 반사광",
        ["arccw.cvar.glare.desc"]                = "조준 시 조준경에서 반사광이 발생할지에 대한 여부입니다.",
        ["arccw.cvar.shake"]                     = "화면 흔들림",
        ["arccw.cvar.shake_info"]                = "무기 발포 시 공격적인 화면 흔들림을 발생실키지에 대한 여부입니다.",
        ["arccw.cvar.2d3d"]                      = "플로팅 도움말",
        ["arccw.cvar.2d3d_info"]                 = "떨어진 무기에 도움말을 띄울지에 대한 여부입니다.",
        ["arccw.cvar.attinv_hideunowned"]        = "소지하고 있지 않은 부착물 보이지 않기",
        ["arccw.cvar.attinv_darkunowned"]        = "소지하고 있지 않은 부착물을 회색으로 표시하기",
        ["arccw.cvar.attinv_onlyinspect"]        = "커스터마이징 UI 감추기",
        ["arccw.cvar.attinv_simpleproscons"]     = "간단한 장단점 표기",
        ["arccw.cvar.attinv_closeonhurt"]        = "피해를 입을 시 메뉴를 닫기",
        ["arccw.cvar.language"]                  = "언어",
        ["arccw.cvar.language_info"]             = "현재 사용중인 언어를 재정의합니다. 비워둘 시 gmod_language cvar의 값을 사용합니다.",
        ["arccw.cvar.font"]                      = "폰트",
        ["arccw.cvar.font_info"]                 = "현재 UI에 사용되는 허드를 재정의합니다. 비워둘 시 기본 폰트를 사용합니다.",
        -- ArcCW_Options_Perf
        ["arccw.performance"]                    = "이 옵션들은 성능에 영향을 끼칠 수 있습니다.",
        ["arccw.cvar.cheapscopes"]               = "성능 개선형 조준경",
        ["arccw.cvar.cheapscopes.desc"]          = "조준경의 품질을 크게 저하키지만 성능을 크게 향상시킵니다.\n장거리 조준 시 조준 지점의 해상도가 떨어집니다!",
        ["arccw.cvar.flatscopes"]                = "평면 조준경",
        ["arccw.cvar.flatscopes.desc"]           = "매우 높은 성능 향상을 위해.\n전통적인 조준경은 그다지 인상적이진 않지만, 성능 향상에는 매우 큰 이점이 있습니다.",
        ["arccw.cvar.muzzleeffects"]             = "월드 머즐 이펙트 활성화",
        ["arccw.cvar.fastmuzzles"]               = "저성능 머즐 이펙트",
        ["arccw.cvar.shelleffects"]              = "월드 케이스 이펙트 활성화",
        ["arccw.cvar.att_showothers"]            = "월드 부착물 표시",
        ["arccw.cvar.shelltime"]                 = "케이스 라이프타임",
        ["arccw.cvar.blur"]                      = "커스텀 블러",
        ["arccw.cvar.blur_toytown"]              = "조준 블러",
        ["arccw.cvar.visibility"]                = "월드 모델 표시",
        ["arccw.cvar.visibility.desc"]           = "무기의 부착물이 지정된 범위를 넘어서는 경우 렌더링 하지 않습니다. -1 지정 시 거리 제한 없음.",
        -- ArcCW_Options_Viewmodel
        ["arccw.cvar.vm_coolsway"]               = "커스텀 스윙",
        ["arccw.cvar.vm_coolview"]               = "커스텀 카메라 움직임",
        ["arccw.cvar.vm_right"]                  = "뷰 모델 오른쪽",
        ["arccw.cvar.vm_forward"]                = "뷰 모델 앞",
        ["arccw.cvar.vm_up"]                     = "뷰 모델 위",
        ["arccw.cvar.vm_offsetwarn"]             = "경고! 뷰 모델의 오프셋 설정은 겹침 또는 예측할 수 없는 효과를 만들 수 있습니다!",
        ["arccw.cvar.vm_sway_sprint"]            = "달리기 흔들림", -- This is intentionally flipped
        ["arccw.cvar.vm_bob_sprint"]             = "달리기 스윙", -- Ditto
        ["arccw.cvar.vm_swaywarn"]               = "커스텀 스윙이 활성화된 경우에만 적용됩니다.",
        ["arccw.cvar.vm_lookymult"]              = "수평 바라보기 스윙",
        ["arccw.cvar.vm_lookxmult"]              = "수직 바라보기 스윙",
        ["arccw.cvar.vm_swayxmult"]              = "오른쪽 흔들림",
        ["arccw.cvar.vm_swayymult"]              = "앞 흔들림",
        ["arccw.cvar.vm_swayzmult"]              = "위 흔들림",
        ["arccw.cvar.vm_swaywigglemult"]         = "행동 흔들림",
        ["arccw.cvar.vm_swayspeedmult"]          = "흔들림 속도",
        ["arccw.cvar.vm_swayrotatemult"]         = "흔들림 회전",

        ["arccw.cvar.vm_accelmult"]              = "스윙 강도",
        ["arccw.cvar.vm_viewwarn"]               = "커스텀 카메라 움직임이 활성화된 경우에만 적용됩니다.",
        ["arccw.cvar.vm_coolviewmult"]           = "시점 움직임 배율",
        -- ArcCW_Options_Crosshair
        ["arccw.crosshair.tfa"]                  = "TFA",
        ["arccw.crosshair.cw2"]                  = "CW 2.0",
        ["arccw.crosshair.cs"]                   = "Counter-Strike",
        ["arccw.crosshair.light"]                = "Lightweight",
        ["arccw.cvar.crosshair"]                 = "조준점 활성화",
        ["arccw.cvar.crosshair_length"]          = "조준점 길이",
        ["arccw.cvar.crosshair_thickness"]       = "조준점 두께",
        ["arccw.cvar.crosshair_gap"]             = "조준점 갭 스케일",
        ["arccw.cvar.crosshair_dot"]             = "중앙 점 표시",
        ["arccw.cvar.crosshair_shotgun"]         = "샷건 분산도 표시",
        ["arccw.cvar.crosshair_equip"]           = "(총기가 아닌) 장비의 분산도 표시",
        ["arccw.cvar.crosshair_static"]          = "정적 조준점",
        ["arccw.cvar.crosshair_clump"]           = "CW2 스타일식 클럼프 원 사용",
        ["arccw.cvar.crosshair_clump_outline"]   = "클럼프 원 외곽선",
        ["arccw.cvar.crosshair_clump_always"]    = "클럼프 원 상시 활성화",
        ["arccw.cvar.crosshair_clr"]             = "조준점 색상",
        ["arccw.cvar.crosshair_outline"]         = "외곽선 크기",
        ["arccw.cvar.crosshair_outline_clr"]     = "외곽선 색상",
        ["arccw.cvar.scope_clr"]                 = "조준경 조준점 색상",
        -- ArcCW_Options_Mults
        ["arccw.cvar.mult_damage"]               = "피해",
        ["arccw.cvar.mult_npcdamage"]            = "NPC 피해",
        ["arccw.cvar.mult_range"]                = "사거리",
        ["arccw.cvar.mult_recoil"]               = "반동",
        ["arccw.cvar.mult_penetration"]          = "관통력",
        ["arccw.cvar.mult_hipfire"]              = "비조준 확산",
        ["arccw.cvar.mult_movedisp"]             = "이동 확산",
        ["arccw.cvar.mult_reloadtime"]           = "재장전 시간",
        ["arccw.cvar.mult_sighttime"]            = "정조준 시간",
        ["arccw.cvar.mult_defaultclip"]          = "기본 탄약",
        ["arccw.cvar.mult_attchance"]            = "랜덤 부착물 확률",
        
        --[[ What?
        ["arccw.cvar.mult_damage"]               = "Damage",
        ["arccw.cvar.mult_npcdamage"]            = "NPC Damage",
        ["arccw.cvar.mult_range"]                = "Range",
        ["arccw.cvar.mult_recoil"]               = "Recoil",
        ["arccw.cvar.mult_penetration"]          = "Penetration",
        ["arccw.cvar.mult_hipfire"]              = "Hip Dispersion",
        ["arccw.cvar.mult_movedisp"]             = "Move Dispersion",
        ["arccw.cvar.mult_reloadtime"]           = "Reload Time",
        ["arccw.cvar.mult_sighttime"]            = "ADS Time",
        ["arccw.cvar.mult_defaultclip"]          = "Default Clip",
        ["arccw.cvar.mult_attchance"]            = "Random Att. Chance",
        ]]
        
        -- ArcCW_Options_Atts
        ["arccw.attdesc1"]                       = "ArcCW는 ACT3와 비슷한 부착물 인벤토리를, CW2와 비슷한 부착물 잠금 시스템을, TFA와 비슷한 제한없이 부착물을 제공합니다.",
        ["arccw.attdesc2"]                       = "ACT3 스타일의 부착물 인벤토리 동작에 대한 모든 옵션을 버리십시오.",
        ["arccw.cvar.attinv_free"]               = "공짜 부착물",
        ["arccw.cvar.attinv_lockmode"]           = "부착물 잠금",
        ["arccw.cvar.attinv_loseondie.desc"]     = "부착물 소실 모드:\n0 - 비활성화\n1 = 사망 시 제거\n2 = 사망 시 부착물 박스 드랍",
        ["arccw.cvar.attinv_loseondie"]          = "부착물 소실 모드",
        ["arccw.cvar.atts_pickx.desc"]           = "Pick X는 무기별 부착 가능한 부착물에 대한 제한하는 용도입니다.\n0 = 제한 없음.",
        ["arccw.cvar.atts_pickx"]                = "Pick X",
        ["arccw.cvar.enable_dropping"]           = "부착물 드랍",
        ["arccw.cvar.atts_spawnrand"]            = "스폰 시 랜덤 부착물",
        ["arccw.cvar.atts_ubglautoload"]         = "하단 부착식 무기 자동 장전",
        ["arccw.blacklist"]                      = "블랙리스트 메뉴",
        -- ArcCW_Options_Server
        ["arccw.cvar.enable_penetration"]        = "관통 활성화",
        ["arccw.cvar.enable_customization"]      = "커스터마이징 활성화",
        ["arccw.cvar.truenames"]                 = "트루 네임 (재시작 필요)",
        ["arccw.cvar.equipmentammo.desc"]        = "탄약 종류는 255개로 제한되어 있습니다. 활성화 시 문제가 발생할 수 있습니다. (재시작 필요)",
        ["arccw.cvar.equipmentammo"]             = "무기별 독립 탄약",
        ["arccw.cvar.equipmentsingleton.desc"]   = "싱글톤은 사용 후 인벤토리에서 무기가 제거됩니다. (재시작 필요)",
        ["arccw.cvar.equipmentsingleton"]        = "수류탄 / 장비 싱글톤",
        ["arccw.cvar.equipmenttime"]             = "장비 자폭 시간",
        ["arccw.cvar.throwinertia"]              = "수류탄 초기 가속도",
        ["arccw.cvar.limityear_enable"]          = "연대 제한 활성화",
        ["arccw.cvar.limityear"]                 = "연대 제한",
        ["arccw.cvar.override_crosshair_off"]    = "조준점 강제 비활성화",
        ["arccw.cvar.override_deploychambered"]  = "전개 시 약실 개방",
        ["arccw.cvar.override_barrellength"]     = "총구 벽 가로막힘 활성화",
        ["arccw.cvar.doorbust"]                  = "문 파괴 활성화",
        ["arccw.cvar.desync"]                    = "미동기화식 (Desync) 탄환",
        ["arccw.cvar.desync.desc"]               = "서버와 클라이언트간 탄환의 동기화를 해제합니다. 스프레드 핵을 방지하는데 유용합니다.",
        ["arccw.cvar.weakensounds"]              = "낮은 발포음",
        ["arccw.cvar.weakensounds.desc"]         = "모든 무기의 발포음을 60에서 150 데시벨로 감소시킵니다.",
        
        -- ArcCW_Options_Dev
        ["arccw.dev_info1"]                      = "부착물과 관련된 부분으로 개발자만이 사용할 수 있습니다.",
        ["arccw.dev_info2"]                      = "설정은 저장되지 않습니다.",
        ["arccw.cvar.dev_reloadonadmincleanup"]  = "관리자 클린업 시 리로드",
        ["arccw.cvar.dev_reloadonadmincleanup.desc"]    = "기본 값 : 비활성화\n관리자 클린업이 모든 부착물 데이터를 리로드합니다.",
        ["arccw.cvar.dev_registerentities"]      = "부착물 엔티티 등록",
        ["arccw.cvar.dev_registerentities.desc"] = "기본 값 : 활성화\nArcCW 부착물의 엔티티를 생성합니다. 부착물 데이터 리로드 시간이 증가합니다.",
        ["arccw.cvar.dev_reloadatts"]            = "부착물 데이터 리로드",
        ["arccw.cvar.dev_reloadatts.desc"]       = "부착물 데이터를 리로드합니다. 부착물 수정 후 사용하세요.",
        
        -- TTT Menus
        ["arccw.cvar.attinv_loseondie.help"]     = "활성화된 경우 사망 또는 라운드 종료 시 모든 부착물을 제거합니다.",
        ["arccw.cvar.ammo_detonationmode.help"]  = "탄약 상자 파괴 시 폭발할지에 대한 여부입니다.",
        ["arccw.cvar.equipmenttime.help"]        = "크레모아 같은 전개 가능한 장비에 적용됩니다.",
        ["arccw.cvar.ttt_bodyattinfo"]           = "시체 공격 부착물 정보",
        ["arccw.cvar.ttt_bodyattinfo.help"]      = "활성화 시 시체 수색이 어떠한 부착물을 장비한 무기에 의해 사망하였는지 표시합니다.",
        ["arccw.cvar.ttt_bodyattinfo.desc"]      = "0 - 끄기; 1 - 탐정만 볼 수 있음; 2 - 모두가 볼 수 있음",
        ["arccw.cvar.attinv_free.help"]          = "활성화 시 모든 부착물을 사용할 수 있습니다. 커스터마이징 모드에 따라 제한될 수 있습니다.",
        ["arccw.cvar.attinv_lockmode.help"]      = "활성화 시 습득한 부착물이 모든 무기에서 해금됩니다.",
        ["arccw.cvar.ttt_weakensounds"]          = "낮은 발포음",
        ["arccw.cvar.ttt_weakensounds.help"]     = "모든 무기의 발포음을 20 데시벨로 감소시킵니다.",
        ["arccw.cvar.enable_customization.help"] = "비활성화 시 커스터마이징을 제한합니다. 이 설정은 커스터마이징 모드 설정을 무시합니다.",
        ["arccw.cvar.ttt_replace"]               = "자동 무기 대체",
        ["arccw.cvar.ttt_replaceammo"]           = "자동 탄약 대체",
        ["arccw.cvar.ttt_atts"]                  = "랜덤 부착물",
        ["arccw.cvar.ttt_customizemode"]         = "커스터마이징 모드",
        ["arccw.cvar.ttt_customizemode.desc"]    = "0 - 제한 없음; 1 - 제한; 2 - 게임 시작 전에만 가능; 3 - 트레이더 또는 탐정만 가능",
        ["arccw.cvar.ttt_rolecrosshair"]         = "역할 기반 조준점 색상 활성화",
        ["arccw.cvar.ttt_inforoundstart"]        = "라운드 시작 정보 활성화",
    },
}

local lang = ArcCW.GetLanguage()
if !ArcCW.PhraseTable[lang] then lang = "en" end

for key, value in pairs(ArcCW.PhraseTable[lang]) do
    if key != "" and (value and value != "") then language.Add(key, value) end
end
